# Site settings
name: Kai He
email: hekind@qq.com
author: Kai He
url: http://www.hekind.cn
resume_site: http://www.hekind.cn/resume.pdf
github: https://github.com/hekind/
baseurl: ""
description: Deep Learning, Machine Learning, Data Mining, Bioinformatics.
# meta_description: 
# motto: 
# banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: hekind

# Build settings
markdown: kramdown

baidu_analysis: 6e7ab9bc735ede55a0c38044622358e7
revolvermaps: 04ytl5o2xjt